# UI Colors (extended)
accent = "#7c89b0"
cursor = "#999999"

# Primary colors
foreground = "#999999"
background = "#010103"

# Selection colors
selection_foreground = "#010103"
selection_background = "#999999"

# Normal colors (ANSI 0-7)
color0 = "#010103"
color1 = "#996b6e"
color2 = "#58846e"
color3 = "#708b68"
color4 = "#7c89b0"
color5 = "#a588ab"
color6 = "#70a8b1"
color7 = "#999999"

# Bright colors (ANSI 8-15)
color8 = "#5a5a61"
color9 = "#c28d91"
color10 = "#599779"
color11 = "#799d6d"
color12 = "#8698cc"
color13 = "#ba93c2"
color14 = "#6bbbc8"
color15 = "#a8a8af"
