hl.config({
    general = {
        col = {
            active_border = "rgb({blue.strip})",
        },
    },
    group = {
        col = {
            border_active = "rgb({blue.strip})",
        },
    },
})
