[colors]
[colors.primary]
background = "#060A00"
foreground = "#F7F4E9"

[colors.normal]
black   = "#060A00"
red     = "#BC837F"
green   = "#77906E"
yellow  = "#B0BD90"
blue    = "#4c8396"
magenta = "#b66342"
cyan    = "#629AA2"
white   = "#F7F4E9"

[colors.bright]
black   = "#5e605a"
red     = "#e7a6a1"
green   = "#99b78a"
yellow  = "#cadaa0"
blue    = "#6ba8c1"
magenta = "#e38559"
cyan    = "#81c1cb"
white   = "#f5ecc1"

[colors.cursor]
text   = "#060A00"
cursor = "#F7F4E9"
