# UI Colors (extended)
accent = "#4c8396"
cursor = "#F7F4E9"

# Primary colors
foreground = "#F7F4E9"
background = "#060A00"

# Selection colors
selection_foreground = "#060A00"
selection_background = "#F7F4E9"

# Normal colors (ANSI 0-7)
color0 = "#060A00"
color1 = "#BC837F"
color2 = "#77906E"
color3 = "#B0BD90"
color4 = "#4c8396"
color5 = "#b66342"
color6 = "#629AA2"
color7 = "#F7F4E9"

# Bright colors (ANSI 8-15)
color8 = "#5e605a"
color9 = "#e7a6a1"
color10 = "#99b78a"
color11 = "#cadaa0"
color12 = "#6ba8c1"
color13 = "#e38559"
color14 = "#81c1cb"
color15 = "#f5ecc1"
