# Background and foreground colors
background = #000000
foreground = #D9C4AB

# Standard colors
palette = 0=#000000
palette = 1=#c45146
palette = 2=#977169
palette = 3=#977648
palette = 4=#6174b4
palette = 5=#9b6b92
palette = 6=#6679bc
palette = 7=#D9C4AB

# Bright colors
palette = 8=#686163
palette = 9=#f47161
palette = 10=#bf9489
palette = 11=#bf9a5d
palette = 12=#8396e8
palette = 13=#c58cbe
palette = 14=#889bf1
palette = 15=#f5ce95
