# Background and foreground colors
background = #010103
foreground = #999999

# Standard colors
palette = 0=#010103
palette = 1=#996b6e
palette = 2=#58846e
palette = 3=#708b68
palette = 4=#7c89b0
palette = 5=#a588ab
palette = 6=#70a8b1
palette = 7=#999999

# Bright colors
palette = 8=#5a5a61
palette = 9=#c28d91
palette = 10=#599779
palette = 11=#799d6d
palette = 12=#8698cc
palette = 13=#ba93c2
palette = 14=#6bbbc8
palette = 15=#a8a8af
