$color = rgba(0, 0, 0, 1)
$inner_color = rgba(0, 0, 0, 0.66)
$outer_color = rgba(155, 107, 146, 1)
$font_color = rgba(217, 196, 171, 1)
$placeholder_color = rgba(217, 196, 171, 0.7)
$check_color = rgba(102, 121, 188, 1)
