$color = rgba(6, 10, 0, 1)
$inner_color = rgba(6, 10, 0, 0.66)
$outer_color = rgba(182, 99, 66, 1)
$font_color = rgba(247, 244, 233, 1)
$placeholder_color = rgba(247, 244, 233, 0.7)
$check_color = rgba(98, 154, 162, 1)
