
require("hyprland.lib")
require("hyprland.variables")
if is_file_exists(HOME .. "/.config/hypr/custom/variables.lua") then
    require("custom.variables")
end

-- local qsScripts = "$HOME/.config/quickshell/$qsConfig/scripts"
-- local hyprScripts = "$HOME/.config/hypr/hyprland/scripts"
local shutdownCMD = "exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit"
local qsIpcCall = "qs -c $qsConfig ipc call"
local qsIsAlive = qsIpcCall .. " TEST_ALIVE"

hl.bind("SUPER + SUPER_L", hl.dsp.global("quickshell:searchToggleRelease"), { description = "Shell: Toggle search" })
hl.bind("SUPER + SUPER_R", hl.dsp.global("quickshell:searchToggleRelease"))
hl.bind("SUPER + SUPER_L", hl.dsp.exec_cmd(qsIsAlive .. " || pkill fuzzel || fuzzel"))
hl.bind("SUPER + SUPER_R", hl.dsp.exec_cmd(qsIsAlive .. " || pkill fuzzel || fuzzel"))

h1.bind(" SUPER + Q" exec, $terminal")
h1.bind(" = SUPER, C, killactive")
h1.bind("SUPER, E, exec, $fileManager
h1.bind("SUPER, V, togglefloating,
h1.bind("SUPER, R, exec, $menu

-- # _____________________________
-- # Window Management
-- # _____________________________

h1.bind("SUPER, W, $d close focused window, exec, $KILLACTIVE
h1.bind("Alt, F4, $d close focused window, exec, $KILLACTIVE
h1.bind("SUPER, Delete, $d kill hyprland session, exec, hyde-shell logout
h1.bind("SUPER, T, $d Toggle floating, togglefloating
h1.bind("SUPER, G, $d toggle group, togglegroup
h1.bind("SUPER, F, $d toggle fullscreen, fullscreen
h1.bind("SUPER, L, $d lock screen, exec, hyde-shell lock-session
h1.bind("SUPER Shift, F, $d toggle pin on focused window, exec, hyde-shell window.pin
h1.bind("Control + Alt + Delete", $d logout menu, exec, hyde-shell logoutlaunch
h1.bind("Alt_R, Control_R, $d toggle waybar and reload config, exec, hyde-shell waybar --hide
# h1.bind("ALT_R, Control_R,toggle waybar, exec, killall waybar || waybar # toggle waybar without reloading, this is faster
