-- Color definitions
-- e.g.
-- hl.config({
--     decoration = {
--         col = {
--             active_border   = { colors = {"rgba(33ccffee)", "rgba(00ff99ee)"}, angle = 45 },
--             inactive_border = "rgba(595959aa)",
--         },
--     },
-- })
